app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::any('ajax/image', ['as' => 'ajax-image', 'uses' => 'AjaxController@getImage']);
Route::any('ajax/image/course', 'AjaxController@getImageCourse');
Route::post('/ajax/group/add/{courseId}', 'AjaxController@addGroup');
Route::post('/ajax/group/edit/{groupId}', 'AjaxController@editGroup');
Route::post('/ajax/group/delete/{groupId}', 'AjaxController@deleteGroup');

// Password
Route::get('password/reminder', 'RemindersController@getRemind');
Route::post('password/reminder', 'RemindersController@postRemind');
Route::get('password/reset/{token}', 'RemindersController@getReset');
Route::post('password/reset/', 'RemindersController@postReset');

// User
Route::any('/login', ['as' => 'login', 'uses' => 'UserController@login']);
Route::get('/logout', ['as' => 'logout', 'uses' => 'UserController@logout']);
Route::get('/register', ['as' => 'register', 'uses' => 'UserController@register']);
Route::post('/register', 'UserController@postRegister');
Route::get('/activation/{userId}/{activationCode}', 'UserController@getActivate');

// School
Route::get('/course/add', [
	'before' => 'auth',
	'as' => 'course-add',
	'uses' => 'SchoolController@getAddCourse'
]);
Route::post('/course/add', [
	'before' => 'auth',
	'uses' => 'SchoolController@postAddCourse'
]);
Route::get('/course/edit/{title}', [
	'before' => 'auth|editable_course|isset_course',
	'as' => 'course-edit',
	'uses' => 'SchoolController@getEditCourse'
]);
Route::post('/course/edit/{title}', [
	'before' => 'auth|editable_course|isset_course',
	'uses' => 'SchoolController@postEditCourse'
]);
Route::get('school/{title}', [
	'as' => 'school',
	'uses' => 'SchoolController@index'
]);

// Courses
Route::get('course/{title}', ['as' => 'course', 'uses' => 'CoursesController@show']);
Route::get('course/buy/{groupId}', [
	'as' => 'buy',
	'uses' => 'CoursesController@getBuy'
]);
Route::post('course/buy', ['as' => 'course-buy', 'uses' => 'CoursesController@postBuy']);
Route::get('catalog/{categoryTitle?}/{subcategoryTitle?}', ['as' => 'catalog', 'uses' => 'CoursesController@index']);

// Оплата
Route::post('payment/result', [
	'uses' => 'PaymentController@result'
]);
Route::post('payment/success', [
	'uses' => 'PaymentController@success'
]);
Route::post('payment/fail', [
	'uses' => 'PaymentController@fail'
]);

// Home
Route::get('/', ['as' => 'home', 'uses' => 'CoursesController@index']);

app/models/Course.php
<?php

use Laracasts\Presenter\PresentableTrait;

class Course extends Eloquent
{

	use PresentableTrait;

	public static $validationRules = [
		'title' => 'required|min:2',
		'lessons' => 'required|numeric',
		'duration' => ['required', 'regex:/^\d+([\.|,]\d+)?$/'],
		'category_id' => 'required',
		'level_id' => 'required',
		'age_id' => 'required',
	];
	protected $table = 'courses';
	protected $fillable = [];


	/**
	 * @var string
	 */
	protected $presenter = 'Site\Presenters\CoursePresenter';

	public function category()
	{
		return $this->belongsTo('Category');
	}

	public function school()
	{
		return $this->belongsTo('School');
	}

	public function age()
	{
		return $this->belongsTo('Age', 'age_id');
	}

	public function level()
	{
		return $this->belongsTo('Level');
	}

	public function getFirstImageAttribute($value)
	{
		return array_get($value, 0);
	}

	public function getImagesAttribute($value)
	{
		if ($value) {
			return unserialize($value);
		} else {
			return [];
		}
	}

	public function setImagesAttribute($value)
	{
		$this->attributes['images'] = null;
		if ($value) {
			$this->attributes['images'] = serialize(explode(',', $value));
		}
	}

	public function getMetroAttribute()
	{
		if ($this->location_metro) {
			$matches = [];
			preg_match('/^.*(метро.*)$/', $this->location_metro, $matches);

			return $matches[count($matches) - 1];
		} else {
			return null;
		}
	}

	public function getFirstGroupAttribute()
	{
		return $this->groups->first();
	}

	public function groups()
	{
		return $this->hasMany('Group');
	}

	public function setTitle($value)
	{
		$this->title = trim(strip_tags($value));
		$tempSeoTitle = Translit::get_seo_keyword($this->title, true);
		if ($this->id) {
			$matches = Course::whereSeoTitle($tempSeoTitle)->where('id', '<>', $this->id)->get()->count();
		} else {
			$matches = Course::whereSeoTitle($tempSeoTitle)->get()->count();
		}

		if ($matches) {
			$this->seo_title = $tempSeoTitle . '_' . rand(1, 1000);
		} else {
			$this->seo_title = $tempSeoTitle;
		}
	}

	public function scopeActive($query)
	{
		return $query->whereStatus(1);
	}

	public function scopeSorted($query)
	{
		return $query->orderBy('created_at', 'desc')->orderBy('updated_at', 'desc');
	}

	public function averageSeatsCount()
	{
		$countAll = 0;

		foreach ($this->groups as $group) {
			$countAll += $group->seats_all;
		}

		return round($countAll / count($this->groups));
	}

	public function getTotalDuration()
	{
		return ceil($this->lessons * $this->duration);
	}

	public function metro()
	{
		return $this->belongsTo('MetroStation');
	}

	public function generateSlug()
	{
		$seo_title = Translit::get_seo_keyword($this->title, true);
		while (true)
        {
			$course = self::whereSeoTitle($seo_title)->first();
			if ($course)
            {
				$seo_title = Translit::get_seo_keyword($this->title, true) . '_' . rand(2, 1000);
			}
            else
            {
                return $seo_title;
                break;
            }
		}
	}
}

app/controllers/CoursesController.php
<?php
use Laracasts\Commander\CommanderTrait;
use Site\Commands\Course\BuyCourseCommand;
use Site\Commands\Course\GetCoursesListCommand;
use Site\Transformers\AgeTransformer;
use Site\Transformers\GroupTransformer;
use Site\Transformers\LevelTransformer;

/**
 * Created by Ruslan Koloskov
 * Date: 31.08.2014
 * Time: 13:05
 */
class CoursesController extends BaseController {

    use CommanderTrait;
    /**
     * @var LevelTransformer
     */
    private $levelTransformer;
    /**
     * @var AgeTransformer
     */
    private $ageTransformer;
    /**
     * @var GroupTransformer
     */
    private $groupTransformer;

    /**
     * @param LevelTransformer $levelTransformer
     * @param AgeTransformer   $ageTransformer
     * @param GroupTransformer $groupTransformer
     */
    public function __construct(
        LevelTransformer $levelTransformer,
        AgeTransformer $ageTransformer,
        GroupTransformer $groupTransformer)
    {
        $this->levelTransformer = $levelTransformer;
        $this->ageTransformer   = $ageTransformer;
        $this->groupTransformer = $groupTransformer;
    }

    /**
     * @param null $categoryTitle
     *
     * @return \Illuminate\View\View
     */
    public function index($categoryTitle = null, $subCategoryTitle = null)
    {
        $categoryTitle = trim(strip_tags($categoryTitle));
        $subCategoryTitle = trim(strip_tags($subCategoryTitle));

        $ages      = $this->ageTransformer->transformCollection(Age::all(), true);
        $levels    = $this->levelTransformer->transformCollection(Level::all(), true);
        $metroList = [
            1 => 'Арбатская',
            2 => 'Киевская',
            3 => 'Третьяковская',
        ];

        $mainCats = Category::with([
            'childrens' => function ($q)
            {
                return $q->orderBy('sort');
            }
        ])->mainCats()->sorted()->limit(7)->get();


        $result = $this->execute(GetCoursesListCommand::class, Input::all() + compact('categoryTitle', 'subCategoryTitle'));

        $courses = $result['courses'];
        $command = $result['command'];
        $prices  = $result['prices'];
        $category  = $result['category'];
        $subCategories  = $result['subCategories'];
        $activeCategory  = $result['activeCategory'];

        return View::make('courses.catalog',
            compact('mainCats', 'ages', 'levels', 'prices', 'courses', 'metroList', 'subCategories',
                'category', 'command', 'activeCategory'));
    }

    /**
     * @param $title
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function show($title)
    {
        $course = Course::whereSeoTitle($title)->with([
            'school',
            'groups',
            'category',
            'category.parent',
        ])->first();
        if(!$course)
        {
            return Redirect::route('catalog');
        }

        $groups = $course->groups()->active()->visible()->sorted()->get();

        $closestGroup  = $groups->shift();
        $subCategories = null;

        $commonCourses = Course::with([
            'school',
            'groups',
            'category',
            'category.parent',
        ])->where('category_id', $course->category->id)->take(3)->get();

        return View::make('courses.course_description',
            compact('course', 'groups', 'subCategories', 'commonCourses', 'closestGroup'));
    }

    /**
     * @param $groupId
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function getBuy($groupId)
    {
        $group = Group::with('course', 'course.groups')->find(intval($groupId));

        if(!$group)
        {
            if(Request::header('referrer'))
            {
                return Redirect::back();
            }
            else
            {
                return Redirect::home();
            }
        }

        $course       = $group->course;
        $groups       = $course->groups()->active()->visible()->sorted()->get();
        $groupsSelect = $this->groupTransformer->transformCollection($groups, true);
        $groupsData   = $this->groupTransformer->transformCollection($groups);

        $subCategories = null;

        return View::make('courses.buy', compact('group', 'course', 'groupsSelect', 'groupsData', 'subCategories'));
    }

    /**
     * @return \Illuminate\Http\RedirectResponse
     */
    public function postBuy()
    {
        /**
         * @var Order $order
         */
        $order = $this->execute(BuyCourseCommand::class);

        $url            = Config::get('robokassa.url');
        $MerchantLogin  = Config::get('robokassa.login');
        $OutSum         = number_format($order->amount, 2, '.', '');
        $InvoiceID      = $order->id;
        $Description    = 'Оплата курса ' . $order->group->course->title;
        $SignatureValue = md5(Config::get('robokassa.login') . ':' . number_format($order->amount, 2, '.', '') . ':' . $order->id . ':'
            . Config::get('robokassa.pass1'));
        $Language       = 'ru';

        $query_data = compact('MerchantLogin', 'OutSum', 'InvoiceID', 'SignatureValue', 'Language', 'Description');

        return Redirect::away($url . '?' . http_build_query($query_data));
    }
}

app/views/courses/catalog.blade.php
@extends('layouts.one-column')

@section('title')
	@if(isset($category) && $category)
		:: {{ $category->title }}
	@else
		:: Каталог курсов
	@endif
@stop

@section('submenu')
	@include('includes.main-categories')
@stop

@section('content')

@include('includes.filters')

<div class="tab-content" data-ajax="container"></div>

<div class="ajax-content">
	<div id="courses-list" class="container-fluid">
	@foreach($courses as $course)
		@include('courses.course', $course)
	@endforeach
	</div>

		@if(isset($category) && $category)
			<p>{{ $category->description }}</p>
		@endif
	<div class="container-fluid text-center">
		{{ $courses->links() }}
	</div>
</div>
<div class="col-sm-12">

<h3>Почему стоит выбрать индивидуальные занятия?</h3>

<p>Ваш преподаватель за час до урока пришлет Вам на электронную почту все учебные материалы, которые понадобятся Вам для занятий. Это также позволяет Вам позаниматься самостоятельно перед занятием. Затем Ваше занятие пройдет абсолютно также, как проходит обычный урок в классе. Вы можете попросить преподавателя обратить внимание на какие-то аспекты языка, которые Вам наиболее интересны, либо заниматься полностью по плану преподавателя.</p>

<p>В конце занятия преподаватель даст Вам небольшое домашнее задание, которое, в зависимости от типа упражнения, может быть размещено через один из форумов школы или отправлено по электронной почте преподавателю. Как только преподаватель получит выполненное задание, он уведомит Вас о получении, а к следующему занятию проверит задание.</p>
</div>
@stop

@section('scripts')
<script type="text/javascript" src="/js/catalog.js"></script>
@stop

app/views/courses/course.blade.php
<div class="course @if(isset($fw) and $fw) col-md-12 col-sm-4 @else col-lg-3 col-sm-4 @endif">
    <div class="course-content">
        <div class="course-picture">
            @if($course->images)
                <a target="_blank" href="{{ URL::route('course', [$course->seo_title]) }}" class="photo">
                    <img src="/uploads/course/{{ $course->first_image }}" alt="{{ $course->title }}">
                </a>
            @else
                <a href="{{ URL::route('course', [$course->seo_title]) }}">
                    <img data-src="holder.js/100%x200">
                </a>
            @endif
        </div>
        @include('includes.level-age', $course)
        <div class="course-title">
            <h3>{{ $course->seo_title }}</h3>
        </div>
        <div class="course-rating">
            <div class="course-rating-messages pull-right">
                <i class="fa fa-comment-o"></i> 9 Отзывов
            </div>
            <div class="course-rating-label">Рейтинг курса</div>
            <div class="course-rating-stars">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
            </div>
        </div>
        <div class="course-description">
            {{ str_limit($course->short_description, 250, '...') }}
        </div>
        <div class="course-group">
            <div class="course-group-label">Ближайший курс</div>
            <div class="course-group-date">{{ $course->first_group->present()->courseBegins }}</div>
        </div>
        <div class="course-price">
            <div class="course-order pull-left"><a href="{{ URL::route('buy', [$course->first_group->id]) }}" class="btn btn-success">Записаться</a></div>
            <div class="course-price-amount pull-right"><span>{{ number_format($course->first_group->price, 0, '.', ' ') }}</span> <i class="fa fa-rouble"></i></div>
            <div class="clearfix"></div>
        </div>
        <div class="course-more-btn">
            <a href="{{ URL::route('course', [$course->seo_title]) }}">Подробнее о курсе</a>
        </div>
    </div>
</div>

app/views/courses/course_description.blade.php
@extends('layouts.one-column')

@section('title'):: Курс "{{ $course->title }}"@stop

@section('content')
<div class="col-md-1">
	<div class="back-to-catalog">
		<a href="/catalog" class="btn btn-default btn-block back-btn"><i class="fa fa-arrow-left"></i> Назад</a>
	</div>
</div>
<div class="col-md-8">
	<div id="course-block">
		<div class="row">
			<div class="col-lg-7">
                <div class="course-picture">
                    @if($course->images)
                        <a target="_blank" href="{{ URL::route('course', [$course->seo_title]) }}" class="photo">
                            <img src="/uploads/course/{{ $course->first_image }}" alt="{{ $course->title }}">
                        </a>
                    @else
                        <a href="{{ URL::route('course', [$course->seo_title]) }}">
                            <img data-src="holder.js/100%x360">
                        </a>
                    @endif
                </div>
                <div class="course-level-age">
                    <div class="course-age">{{ $course->age->age }}</div><div class="course-level">{{ $course->level->level }}</div>
                </div>
                <div class="course-title">
                    <h3>{{ $course->seo_title }}</h3>
                </div>
                <div class="col-sm-12">
                    <ol class="breadcrumb">
                      <li><a href="/">Главная</a></li>
                      @if($course->category->parent)
                        <li><a href="{{ URL::route('catalog', [
                          'categoryTitle' => $course->category->parent->seo_title,
                           ])  }}">{{ $course->category->parent->title }}</a></li>
                        <li><a href="{{ URL::route('catalog', [
                          'categoryTitle' => $course->category->parent->seo_title,
                           'subCategoryTitle' => $course->category->seo_title
                           ])  }}">{{ $course->category->title }}</a></li>
                        @else
                        <li><a href="{{ URL::route('catalog', [$course->category->seo_title])  }}">{{ $course->category->title }}</a></li>
                        @endif
                      <li class="active">{{ $course->title }}</li>
                    </ol>
                </div>
                <div class="col-sm-12">
                    <h1>{{ $course->title }}</h1>
                </div>
                <div class="col-sm-12">
                    <div class="bottom-border">
                        {{ $course->full_description }}
                    </div>
                </div>
                <div class="col-sm-12">
                    <div class="bottom-border">
                        photos
                    </div>
                </div>
                <div class="col-sm-12">
                    <h2>Организатор</h2>
                </div>

                <div class="col-sm-12">
                    <div class="bottom-border">
                        <div class="row">
                            <div class="col-sm-4">организатор пик</div>
                            <div class="col-sm-8">
                                <h4>{{ $course->school->title }}</h4>
                                {{ $course->school->short_description }}
                                <div class="course-school-more"><a href="#">Подробнее о "{{ $course->school->title }}"</a></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-12">
                    <h2>Как проехать</h2>
                </div>
                <div class="col-sm-12">
                    <div class="bottom-border">
                        <div class="row">
                            <div class="col-sm-6">
                                Адрес:<br />Санкт-Петербург,  Дворцовая набережная, 38
                            </div>
                            <div class="col-sm-6">
                                Телефон:<br/>+7 (812) 710-95-50
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-12">
                    <h2>Отзывы о курсах</h2>
                </div>

                <div class="col-sm-12">
                    <div class="course-rating-stars">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                    </div>
                    9 Отзывов
                </div>

                <div class="col-sm-12">
                    @include('includes.comment')
                    @include('includes.comment')
                    @include('includes.comment')
                    <div class="col-sm-9 col-sm-offset-3"><a href="#">Показать ещё</a></div>
                </div>
                <div class="col-sm-12">
                    <h2>Добавить отзыв о курсе</h2>
                </div>
                <div class="col-sm-12">
                    <div class="course-comment-form">
                        <div class="col-sm-3 text-center">
                            <img src="/img/avatar-stub.png" alt=""/>
                        </div>
                        <div class="col-sm-9">
                            <div class="form-group col-sm-6">
                                <input type="text" name="name" id="inputID" class="form-control" value="" title="" required="required" placeholder="Ваше имя" >
                            </div>
                            <div class="form-group col-sm-12">
                                <input type="text" name="name" id="inputID" class="form-control" value="" title="" required="required" placeholder="Ваше впечатление от курса" >
                            </div>
                            <div class="form-group col-sm-12">
                                <textarea class="form-control" rows="3"  placeholder="Текст отзыва"></textarea>
                            </div>
                        </div>
                        <div class="col-sm-9 col-sm-offset-3">
                            <div class="col-sm-4">Поставте оценку</div>
                            <div class="col-sm-8">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                        </div>
                        <div class="col-sm-9 col-sm-offset-3"><a href="#" class="btn btn-success btn-lg">Оставить отзыв</a></div>
                    </div>
                </div>
                <div class="col-sm-12"><hr/></div>
                <div class="col-sm-12">
                    @include('includes.course-closest', ['withBorder' => true])
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="course-groups" class="col-lg-5">
                <div class="course-rating">
                    <div class="course-rating-label">Рейтинг курса</div>
                    <div class="course-rating-stars">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                    </div>
                </div>
                @include('includes.course-closest', ['withBorder' => false])
                <div class="course-groups-block">
                    <div class="course-groups-block-label">Следующие курсы</div>
                    @foreach($groups as $group)
                    @include('includes.course-group', $group)
                    @endforeach
                </div>
                <div class="course-group-time">
                    * время курса ~ {{ $course->getTotalDuration() }} @choice('час|часа|часов', $course->getTotalDuration())
                </div>
                <div class="course-group-share">
                    Поделиться В F T О M
                </div>
            </div>
            <div class="col-lg-5 course-groups-chevron hidden-md hidden-sm hidden-xs"></div>
            <div class="clearfix"></div>
		</div>
	</div>
</div>
<div class="col-md-3">
    <h1>Похожие курсы</h1>
    @foreach($commonCourses as $course)
    		@include('courses.course', ['course' => $course, 'fw' => true])
    	@endforeach
</div>
{{--<link rel="stylesheet" type="text/css" href="/css/jquery.datetimepicker.css" />--}}
	{{--<div class="course row">--}}
		{{--<div class="card-wrap">--}}
			{{--<div class="card">--}}
				{{--@if($course->images)--}}
					{{--<a target="_blank" href="" class="photo">--}}
						{{--<img src="/uploads/course/{{ $course->first_image }}" alt=""/>--}}
					{{--</a>--}}
				{{--@endif--}}
				{{--<br>--}}
				{{--<button type="button" class="btn btn-success">Записаться</button>--}}
			{{--</div>--}}
			{{--<div class="clearfix"></div>--}}
		{{--</div>--}}
		{{--<div class="info">--}}
			{{--<div class="row">--}}
				{{--@if($course->groups && !$course->groups->isEmpty())--}}
				{{--<div class="price">--}}
					{{--<span class="value">{{ number_format($course->first_group->price, 2, '.', ' ') }}</span>--}}
				{{--</div>--}}
				{{--@endif--}}
				{{--<h1>{{ $course->title }}</h1>--}}
				{{--<br>--}}
				{{--<div class="description">--}}
					{{--<h3 class="title">Короткое описание</h3>--}}
					{{--<p>{{ $course->short_description }}</p>--}}
				{{--</div>--}}
				{{--<div class="description">--}}
					{{--<h3 class="title">Возраст</h3>--}}
					{{--<p>{{ $course->age->age }}</p>--}}
				{{--</div>--}}
				{{--@if($course->level)--}}
				{{--<div class="description">--}}
                    {{--<h3 class="title">Уровень</h3>--}}
                    {{--<p>{{ $course->level->level }}</p>--}}
                {{--</div>--}}
                {{--@endif--}}
				{{--@if($course->groups && !$course->groups->isEmpty())--}}
				{{--<div class="description">--}}
					{{--<h3 class="title">Среднее количество мест</h3>--}}
					{{--<p>{{ $course->averageSeatsCount() }}</p>--}}
				{{--</div>--}}
				{{--@endif--}}
				{{--<div class="school-info">--}}
					{{--<h3 class="title">{{ $course->school->title }}</h3>--}}
					{{--@if($course->school && $course->school->images)--}}
						{{--<div class="school-info-image">--}}
							{{--<img src="{{ $course->school->first_image }}" alt="{{ $course->school->title }}"/>--}}
						{{--</div>--}}
					{{--@endif--}}
					{{--<div class="school-info-text">--}}
						{{--<p>Короткое описание Короткое описание Короткое описание Короткое описание Короткое описание Короткое описание Короткое описание Короткое описание Короткое описание Короткое описание Короткое описание Короткое описание Короткое описание Короткое описание Короткое описание</p>--}}
					{{--</div>--}}
					{{--<div class="clearfix"></div>--}}
				{{--</div>--}}
				{{--@if ($groups->count())--}}
				{{--<div class="description">--}}
					{{--<table class="course-table">--}}
						{{--<tr>--}}
							{{--<th>Время начала</th>--}}
							{{--<th>Кол-во уроков</th>--}}
                            {{--<th>Кол-во свободных мест</th>--}}
							{{--<th>Цена</th>--}}
							{{--<th></th>--}}
						{{--</tr>--}}
						{{--@foreach($groups as $group)--}}
						{{--<tr>--}}
							{{--<td>{{ $group->begins }}</td>--}}
							{{--<td>{{ $group->lessons }}</td>--}}
							{{--<td>{{ $group->seats_all - $group->seats_busy }}</td>--}}
							{{--<td>${{ number_format($group->price, 2, '.', ' ') }}</td>--}}
							{{--<td>--}}
								{{--<a class="btn btn-error" href="{{ URL::route('buy', [$group->id]) }}">Оплатить</a>--}}
							{{--</td>--}}
						{{--</tr>--}}
						{{--@endforeach--}}
					{{--</table>--}}
				{{--</div>--}}
				{{--@endif--}}
				{{--<div class="description">--}}
					{{--<h3 class="title">Рейтинг</h3>--}}
					{{--<p class="rating">--}}
						{{--<span>☆</span><span>☆</span><span>☆</span><span class="not">☆</span><span class="not">☆</span>--}}
					{{--</p>--}}
				{{--</div>--}}
			{{--</div>--}}
		{{--</div>--}}
		{{--<div class="meta">--}}
			{{--<div class="place">--}}
				{{--<span class="icons icon-place"></span>{{ $course->metro }}--}}
			{{--</div>--}}
			{{--<div class="clearfix"></div>--}}
		{{--</div>--}}
		{{--<div class="clearfix"></div>--}}
	{{--</div>--}}
@stop
@section('scripts')
<script src="/js/jquery.datetimepicker.js" type="text/javascript"></script>
<script src="/js/add-group.constructor.js" type="text/javascript"></script>
<script src="/js/checkboxes.style.js" type="text/javascript"></script>
@stop